version: '3.8'

services:
  # Laravel Backend
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Add this line
    networks:
      - backend-network
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=event_reminder
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - QUEUE_CONNECTION=rabbitmq
      - RABBITMQ_HOST=rabbitmq
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  # Vue.js Frontend
  vue:
    build:
      context: .
      dockerfile: Dockerfile.vue
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules  # Preserve node_modules
    environment:
      - HOST=0.0.0.0
    networks:
      - backend-network
  # MySQL Database
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: event_reminder
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network      

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - app

volumes:
  mysql_data:
  
networks:
  backend-network:
    driver: bridge